// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pebitpgeuvllnbsdhmei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlYml0cGdldXZsbG5ic2RobWVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNDY5MTEsImV4cCI6MjA3NDcyMjkxMX0.n1FJCXaE2_ARQYRvh86GOMNPBx9Dtuz9JR3CKwSTr5Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});