// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvpbddlylwwtkbnilzvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2cGJkZGx5bHd3dGtibmlsenZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NzY4MTUsImV4cCI6MjA3NDU1MjgxNX0.9iMnvpdygqCs3Z6NIK6MmTz_7PnpguSAu9YUveA0S2g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});